<?php


include "base.php";

class Machine{
    public $brand;
    function sayHello(){
        echo "hello I am a machine <br>";
    }
}
class Transportation extends Machine{
    public $type;

    # overriding --> 2 functions with the same name in
    # 2 classes have inheritance relarion
    function sayHello(){
        # call parent function
        parent::sayHello();
        echo "hello I am a transportation";
    }
    final function canMove(){  # this method cannot be overridden
        echo "I can move";
    }

}

$t = new Transportation();
var_dump($t);
$t->sayHello();



################################3
final class Car extends Transportation {
    public $model;
    function sayHello()
    {
        parent::sayHello();
        // TODO: Change the autogenerated stub
        echo "Called from the Car class";
    }

//    function canMove(){ # server error
//
//    }
}

$c = new Car();
echo "<br>";
$c->canMove();

//class BMW extends Car{ # extend from final class
//
//}